contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),

    # contact
    path('contact/<int:contact_id>/detail/', views.contact, name='contact'),
    path('contact/create/', views.create, name='create'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),
    
    # user
    path('user/create/', views.register, name='register'),
    path('user/login/', views.login_view, name='login'),
    path('user/logout/', views.logout_view, name='logout')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contact.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from typing import Any
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name.capitalize()


class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=50, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self) -> str:
        return self.first_name.capitalize() + ' ' + self.last_name.capitalize()

contact/forms.py
from contact.models import Contact
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(
        required=True,
        min_length=3
    )

    last_name = forms.CharField(
        required=True,
        min_length=3
    )

    email = forms.EmailField(
        required=True,
        min_length=3
    )

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email', 'username', 'password1', 'password2'
        )
    
    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error('email', ValidationError('E-mail already exists.'))


class ContactForm(forms.ModelForm):
    picture = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'accept': 'image/*'
            }
        )
    )

    class Meta:
        model = Contact
        fields = ('first_name', 'last_name', 'phone', 
                  'email', 'description', 'category', 'picture')
        # widgets = {
        #     'first_name': forms.TextInput({
        #         'class': 'class-a class-b'
        #     })
        # }
    
    def clean(self) -> dict[str, any]:
        first_name: str = self.cleaned_data.get('first_name')
        last_name: str = self.cleaned_data.get('last_name')

        if first_name.upper() == last_name.upper():
            self.add_error('first_name', ValidationError("First name can't be the same as the last name"))
            self.add_error('last_name', ValidationError("Last name can't be the same as the first name"))

        return super().clean()
    
    def clean_first_name(self):
        first_name: str = self.cleaned_data.get('first_name')
        
        # if first_name.upper() in ['ATC', 'BOI', 'UTA']:
        #     self.add_error(
        #         'first_name',
        #         ValidationError("Don't use bad words.")
        #     )

        return first_name

contact/views.py
from django.shortcuts import render
from django.http import HttpRequest

def index(request: HttpRequest):
    return render(request, 'contact/index.html')

contact/views/contact_forms.py
from typing import Any, Dict
from django.shortcuts import render, redirect
from django.http import HttpRequest
from contact.forms import ContactForm
from django.urls import reverse
from contact.models import Contact


def create(request: HttpRequest):
    form_action = reverse('contact:create')

    if request.method.upper() == 'POST':
        form = ContactForm(request.POST, request.FILES)

        context = {
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            contact = form.save()
            return redirect('contact:contact', contact_id=contact.pk)

        return render(
        request,
        'contact/create.html',
        context
    )

    context = {
        'form': ContactForm(),
        'form_action': form_action
    }

    return render(
        request,
        'contact/create.html',
        context
    )


def update(request: HttpRequest, contact_id: int):
    form_action = reverse('contact:update', args=(contact_id,))
    
    contact = Contact.objects.filter(pk=contact_id, show=True).first()

    if request.method.upper() == 'POST':
        print('valid')
        form = ContactForm(request.POST, request.FILES, instance=contact)
        context = {
            'form': form,
            'form_action': form_action
        }

        if form.is_valid():
            contact = form.save()
            return redirect('contact:contact', contact_id)
        
        return render(
            request,
            'contact/create.html',
            context
        )
    
    context = {
        'form': ContactForm(instance=contact),
        'form_action': form_action
    }

    return render(
        request,
        'contact/create.html',
        context
    )


def delete(request: HttpRequest, contact_id: int):
    contact = Contact.objects.filter(pk=contact_id, show=True).first()
    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        contact.delete()
        return redirect('contact:index')

    return render(
        request,
        'contact/contact.html',
        {
            'contact': contact,
            'confirmation': confirmation
        }
    )


def login_view(request: HttpRequest):
    return render(
        request,
        'contact/login.html',
        {
            'form': 'form'
        }
    )

contact/views/contact_views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, Http404
from contact.models import Contact
from django.db.models import Q
from django.core.paginator import Paginator


def index(request: HttpRequest):

    contacts = Contact.objects\
        .filter(show=True)\
        .order_by('-id')
    
    page = request.GET.get('page', '1')
    contacts = Paginator(contacts, 10).get_page(page)

    context = {
        'contacts': contacts,
        'page_title': 'Agenda'
    }

    return render(request, 'contact/index.html', context)


def contact(request: HttpRequest, contact_id: int):
    # contact = Contact.objects.get(pk=contact_id)
    contact = Contact.objects.filter(pk=contact_id, show=True).first()

    if contact is None:
        raise Http404('Contact not found')

    context = {
        'contact': contact,
        'page_title': 'Contact - ' + contact.first_name
    }

    return render(request, 'contact/contact.html', context)


def search(request: HttpRequest):
    # search_value = request.GET['q']
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('contact:index')

    contacts = Contact.objects\
        .filter(show=True)\
        .filter(Q(first_name__icontains=search_value) | Q(last_name__icontains=search_value))\
        .order_by('-id')
    
    page = request.GET.get('page', '1')
    contacts = Paginator(contacts, 10).get_page(page)

    context = {
        'contacts': contacts,
        'page_title': 'Agenda',
        'search_value': search_value
    }

    return render(request, 'contact/index.html', context)

contact/views/user_forms.py
from django.http import HttpRequest
from django.shortcuts import render, redirect
from contact.forms import RegisterForm
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth


def register(request: HttpRequest):
    form = RegisterForm()

    if request.method.upper() == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'User succesfully registered')
            return redirect('contact:register')

        return render(
            request,
            'contact/register.html',
            {'form': form}
        )

    return render(
        request,
        'contact/register.html',
        {
            'form': form,
            'messages': messages.get_messages(request)
         }
    )


def login_view(request: HttpRequest):
    form = AuthenticationForm(request)

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            print(user)
        else:
            messages.error(request, 'Login inválido')

    return render(
        request,
        'contact/login.html',
        {
            'form': form
        }
    )

def logout_view(request: HttpRequest):
    auth.logout(request)
    return redirect('contact:login')

contact/templates/contact/contact.html
{% extends 'global/base.html' %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{ contact.first_name }} {{ contact.last_name}}
        </h1>

        <p><b>ID: </b> {{ contact.id }}</p>
        <p><b>E-mail: </b> {{ contact.email }}</p>
        <p><b>Phone: </b> {{ contact.phone }}</p>
        <p><b>Created Date: </b> {{ contact.created_date }}</p>
        <p><b>Description: </b> {{ contact.description }}</p>
        <p><b>Category: </b> {{ contact.category.name }}</p>

        {% if contact.picture %}
            <p>
                <img src="{{ contact.picture.url }}" alt="{{ contact.first_name }} {{ contact.last_name }}">
            </p>
        {% endif %}

        <div class="contact-links">
            <a class="btn btn-link" href="{% url 'contact:update' contact.id %}">Update</a>

            <form action="{% url 'contact:delete' contact.id %}" method="post">
                {% csrf_token %}

                {% if confirmation %}
                    {% if confirmation == 'no' %}
                        <input type="hidden" name="confirmation" value="yes">
                        <button class="btn btn-delete btn-link" type="submit">Confirm Delete</button>
                    {% endif %}
                {% else %}
                    <button class="btn btn-delete btn-link" type="submit">Delete</button>
                {% endif %}
            </form>
        </div>
    </div>
{% endblock content %}

contact/templates/contact/create.html
{% extends 'global/base.html' %}

{% block content %}
    <div class="form-wrapper">

    <h2>Contact</h2>

    <form 
        action="{{ form_action }}"
        method="post"
        enctype="multipart/form-data"
    >
        {% csrf_token %}

        <div class="form-content">
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {{ field.errors }}

                    {% if field.help_text %}
                        <p class="help-text">{{ field.help_text }}</p>
                    {% endif %}
                </div>
            {% endfor %}
        </div>

        <div class="form-content">
            <div class="form-group">
                <button class="btn" type="submit">Send</button>
            </div>
        </div>

    </form>
    </div>
{% endblock content %}

contact/templates/contact/index.html
{% extends 'global/base.html' %}

{% block content %}
{% if contacts %}
    <div class="responsive-table">
        <table class="contacts-table">
            <caption class="table-caption">
                Contacts
            </caption>
            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">First Name</th>
                    <th class="table-header">Last Name</th>
                    <th class="table-header">Phone</th>
                    <th class="table-header">E-mail</th>
                </tr>
            </thead>
            <tbody>
            {% for contact in contacts %}
                <tr class="table-row">
                    <td class="table-cel">
                        <a href="{% url 'contact:contact' contact.id %}" class="table-link">
                            {{ contact.id }}
                        </a>
                    </td>
                    <td class="table-cel">
                        {{ contact.first_name }}
                    </td>
                    <td class="table-cel">
                        {{ contact.last_name }}
                    </td>
                    <td class="table-cel">
                        {{ contact.phone }}
                    </td>
                    <td class="table-cel">
                        {{ contact.email }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
    <div class="single-contact">
        <h2 class="single-contact-name">
            No contact found
        </h2>
    </div>
{% endif %}

{% include 'global/partials/_pagination.html' %}
{% endblock content %}

contact/templates/contact/login.html
{% extends 'global/base.html' %}

{% block content %}
    <div class="form-wrapper">
    
        {% if user.is_authenticated %}
            <p>Você fez login como {{ user }}</p>
            Clique <a href="{% url "contact:logout" %}">aqui</a> para sair
        {% else %}
            <h2>Register</h2>
            <h2>{{ user }}: {{ user.is_authenticated }}</h2>
            {% include 'global/partials/_user_form.html' %}
        {% endif %}
    </div>
{% endblock content %}

contact/templates/contact/register.html
{% extends 'global/base.html' %}

{% block content %}
    <div class="form-wrapper">

    <h2>Register</h2>

    <form 
        action="{{ form_action }}"
        method="post"
    >
        {% csrf_token %}

        <div class="form-content">
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {{ field.errors }}

                    {% if field.help_text %}
                        <p class="help-text">{{ field.help_text }}</p>
                    {% endif %}
                </div>
            {% endfor %}
        </div>

        <div class="form-content">
            <div class="form-group">
                <button class="btn" type="submit">Send</button>
            </div>
        </div>

    </form>
    </div>
{% endblock content %}